<?php

/**
 * @file
 * Functions to support theming in the segallio theme.
 */

use Drupal\Core\Link;

/**
 * Implements hook_preprocess_page().
 */
function segallio_theme_preprocess_page(&$variables) {

  $path = \Drupal::service('path.current')->getPath();
  $variables['active_classes'] = [
    'activity' => $path == '/homepage' ? 'active' : '',
    'map' => $path == '/map' ? 'active' : '',
    'bio' => $path == '/bio' ? 'active' : '',
  ];

}
