<?php

/**
 * Implements hook_migration_plugins_alter().
 */
function segallio_migrate_migration_plugins_alter(&$definitions) {
  $migrations = \Drupal::entityTypeManager()->getStorage('migration')->loadMultiple();

  foreach (array_keys($migrations) as $migration) {
    $definitions[$migration]['source']['path'] = drupal_get_path('module', 'segallio_migrate') . $definitions[$migration]['source']['path'];
  }
}
